import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthSessionProvider } from "@/components/provider/session-provider";
import { QueryProvider } from "@/components/provider/query-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
          
        </NextAuthSessionProvider>
        
        
        
        </body>
    </html>
  );
}
