"""second

Revision ID: 4981f62d1323
Revises: ceb2e2b39cd3
Create Date: 2024-02-15 13:18:38.034870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4981f62d1323'
down_revision: Union[str, None] = 'ceb2e2b39cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Person', sa.Column('lastName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('Person', sa.Column('middleName', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('Person', 'lastname')
    op.drop_column('Person', 'middlename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Person', sa.Column('middlename', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Person', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Person', 'middleName')
    op.drop_column('Person', 'lastName')
    # ### end Alembic commands ###
